# settings audio-remote

[general]
player = "Moode"
server = "192.168.178.79"

[rotary]
timeout = 120
clk_pin = 21
dt_pin = 20
sw_pin = 17

[button]
timeout = 200
button_4 = 6
button_1 = 13
button_2 = 19
button_3 = 26

[rfid]
timeout = 200
led = 12
led_green = 5
led_red = 6
PIN_IRQ = 18
PIN_RST = 22

